### ISSUE TITLE
[FEAT] Support `react-query`'s `useQueries`

### ISSUE THREAD

**Issue by rassie** [pankod/refine#1517]
**Is your feature request related to a problem? Please describe.**

Trying to implement a "number of comments for a post" column (on `simple-rest` data provider), I've found there is no built-in way to make multiple requests, which are more or less required for this to work (see also `ReferenceManyField` from `react-admin`). See https://discord.com/channels/837692625737613362/906206669787234334/939907409634283570 for a bit of discussion.

**Describe the solution you'd like**
There is a `useQueries` in `react-admin`, which seems to do what's required. It would be nice to have a wrapper of some sort -- maybe separate new hooks, maybe built-in support for arrays in `useList` etc. 

**Describe alternatives you've considered**
Currently, I'm building a weird loop around `dataProvider.getList` (see Discord discussion), which feels very low-level and quirky.

**Comment by omeraplak** [comment]
Hey @rassie ,
The way we provide this is with the `useMany` hook. https://refine.dev/docs/api-references/hooks/data/useMany/

If you want to access records `filter-based` `useList` can help you. https://refine.dev/docs/api-references/hooks/data/useList/

**Comment by rilrom** [comment]
Hey @omeraplak,

It doesn't look like the `useMany` hook takes advantage of` useQueries`, which is the recommended option to gain the benefits of React Suspense.

Here's a quote from the [react-query](https://tanstack.com/query/v4/docs/framework/react/guides/parallel-queries#manual-parallel-queries) documentation:

_"When using React Query in suspense mode, this pattern of parallelism does not work, since the first query would throw a promise internally and would suspend the component before the other queries run. To get around this, you'll either need to use the useQueries hook (which is suggested) or orchestrate your own parallelism with separate components for each useQuery instance (which is lame)."_

Does Refine have the ability to take advantage of Suspense?
