### ISSUE TITLE
Building a B2C Data intensive application using React and React Native

### ISSUE THREAD

**Issue by nirmaanlabs** [pankod/refine#1699]
I am launching an MVP Web Application. We are at the phase of picking up right library 

1. Where use will Input/Edit/View data (Text/Media/Number) on daily basis
2. User will see graphs after completion of Task/Project

We are using AWS Cognito, Hasura, React (Web) and React Native (Mobile)

My question 

1. Do you have any use case study or examples considering my technology and scenarios?
2. Are there any example for AWS Cognito, Hasura React (Web)?

**Comment by omeraplak** [comment]
Hey @nirmaanlabs ,
Congratulations on your new project. 

1. Refine is a Headless React framework. Therefore, it does not provide you with any UI elements, but it is designed in such a way that you can use it in perfect harmony with UI frameworks/libraries.

We have an official package for Ant Design. I think it will be a good start for you. (We will announce our Material UI support very soon).

Our Ant design tutorial: https://refine.dev/docs/ui-frameworks/antd/tutorial/
Our Tailwind tutorial: https://refine.dev/docs/core/tutorial/

2. Due to its Refine approach, it is completely agnostic, so it can be used with all technologies. We do not have built-in AWS Cognito support, but as far as I can see from our Discord Community, there are people who have integrated and used it before.
Our Hasura DataProvider support is offered as built-in. You can checkout our Hasura example here, https://refine.dev/docs/examples/data-provider/hasura/

I hope I was able to help you choose the right technologies for your project. Please feel free to contact us if you have any questions!

Happy hacking!

**Comment by DVGY** [comment]
@omeraplak Thanks for your response. 
Can refine be integrated with React Native also ?

**Comment by omeraplak** [comment]
Hey @DVGY ,
We haven't tried it, but we will in the future. It is not among our priorities for now, if you try and have problems we will be happy to help.

maybe this comment will be useful for you,
https://github.com/pankod/refine/issues/1531#issuecomment-1086609764

**Comment by DVGY** [comment]
@omeraplak  Thanks. 
Refine is a great framework. Thank you and your team to make it opensource

**Comment by omeraplak** [comment]
> @omeraplak Thanks. Refine is a great framework. Thank you and your team to make it opensource

Thank you very much 🔥 We've just started, let's make Refine the best framework together! 🚀
