### ISSUE TITLE
[BUG] Module '"casbin.js"' has no exported member 'newModel'.

### ISSUE THREAD

**Issue by Thirumalai08** [pankod/refine#2140]
While importing from newModel from casbin.js it throws error Module has no export member.

**Screenshots**
![image](https://user-images.githubusercontent.com/50919570/178724658-93bf2c2a-9a7e-47a9-b8a5-b11f0bc660f9.png)

**Desktop (please complete the following information):**
 - OS: Wndows
 - Browser chrome
 - Used dataProvider hasura

**Comment by salihozdemir** [comment]
Hello @Thirumalai08 ,
Thanks for issue, we hadn't noticed.

I created a PR for you issue. In this PR we use [`node-casbin`](https://github.com/casbin/node-casbin) instead of [`casbin.js`](https://github.com/casbin/casbin.js). Because `casbin.js` is not maintaining by contributors. 

There are little changes in PR, you can look up in [here](https://github.com/pankod/refine/pull/2141/files).

Another important point is that `casbin` packages doesn't support react-script 5 so I downgraded the example to react-script 4.

Hope this helps.
