### ISSUE TITLE
[BUG] Returning 401 error when click save button on Add Address form 

### ISSUE THREAD

**Issue by sevkioruc** [pankod/refine#2822]
### Describe the bug

Users cannot save their addresses

### Steps To Reproduce

1. Go to Store page
2. Login
3. Click user avatar in top right corner
4. Click My Adresses option
5. Click `+` sign in New Address area
6. Fill the form
7. Click save button
8. Check your http request on Network tab in the developer tool 

### Expected behavior

Users should be able to register their addresses

### Screenshot

![image](https://user-images.githubusercontent.com/33834689/196552330-138d0923-43f5-48b4-939d-58141b9da029.png)

**Comment by aliemir** [comment]
Same also happens when you open your cart and it sends `me` request. Might be an issue related to a version update on medusa side (can be backend/server related or about frontend packages). We need to investigate this further to resolve once for all. Happily there's a workaround for the address field and this is not a blocker for the store; users can still add shipping addresses when processing their order.

Thank you @sevkioruc for the issue 🙏 🙏

**Comment by aliemir** [comment]
Assigning @omeraplak to have a look at the medusa side for any inconsistencies. 🚀

**Comment by omeraplak** [comment]
Hey @aliemir @sevkioruc ,
I've fixed this issue. The problem is that medusa is using cookies for authorization. `store.refine.dev` was used for the auth domain, while `api.store.refine.dev` was used for other requests. This prevented the sharing of cookies.
